### ISSUE TITLE
Practica1_Realidad.Aumentada

### ISSUE THREAD

**Issue by Karina-Vsqz** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Karina-Vsqz#2]
[Practica1_Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Karina-Vsqz/files/6141448/Practica1_Realidad.Aumentada.pdf)

**Comment by ObedG** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien Hecho y revisado
